name: GitHub Crawler Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  crawl-stars:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: crawler_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run Database Migrations
        env:
          SYNC_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/crawler_db
        run: |
          alembic upgrade head

      - name: Run Crawler
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/crawler_db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/crawl.py --count 100000

      - name: Export Database to CSV
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/crawler_db
        run: |
          python scripts/export_db.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: github-repositories-data
          path: repositories.csv
